"""
ZZZ Mod Fixer - Character Hash Commands
Modular character data for maintainability

This package contains individual character modules, each with their own
hash commands dictionary.
"""

__version__ = '3.1'

CHARACTERS = [
    'Alice',
    'AliceSeaOfTime',
    'Anby',
    'Anton',
    'Aria',
    'AriaAgent',
    'AriaAgentDiscordantNote',
    'AriaDiscordantNote',
    'AstraYao',
    'AstraYaoChandelier',
    'Banyue',
    'Belle',
    'BelleBrillianceOfStars',
    'BelleDelicateSunlight',
    'BelleSummerSkies',
    'Ben',
    'Billy',
    'Burnice',
    'Caesar',
    'Cissia',
    'Corin',
    'Dialyn',
    'Ellen',
    'EllenCampus',
    'Evelyn',
    'Grace',
    'Harumasa',
    'Hugo',
    'JaneDoe',
    'JaneDoeNocturneOfLight',
    'JuFufu',
    'Koleda',
    'Lighter',
    'Lucia',
    'Lucy',
    'LucyPrincessOnHoliday',
    'Lycaon',
    'Manato',
    'ManatoWhiteHeartSilhouette',
    'Miyabi',
    'MiyabiDignifiedBlossom',
    'NangongYu',
    'NangongYuRhapsodyMuse',
    'Nekomata',
    'Nicole',
    'NicoleCutie',
    'Norma',
    'Orphie',
    'PanYinhu',
    'PanYinhuCulinaryJewel',
    'Piper',
    'Promeia',
    'Pulchra',
    'Pyrois',
    'Qingyi',
    'Remielle',
    'RemielleMoonlightWhispers',
    'RemielleSeashadePasSeul',
    'Rina',
    'Seed',
    'Seth',
    'Sigrid',
    'SigridMajesticWavechaser',
    'Soldier0',
    'Soldier11',
    'Soukaku',
    'StarlightBilly',
    'Sunna',
    'SunnaAfternoonTeaBreak',
    'Trigger',
    'Velina',
    'VelinaShadeOfLeisure',
    'Vivian',
    'VivianIrisOfTheShore',
    'Wise',
    'WiseOathOfSkies',
    'WisePeacefulWaves',
    'WiseSoaringCrane',
    'Yanagi',
    'YeShunguang',
    'YeShunguangSword',
    'YeShunguangSwordUlt',
    'YeShunguangTouchOfDawnlight',
    'YeShunguangUlt',
    'Yidhari',
    'Yixuan',
    'YixuanTrailsOfInk',
    'Yuzuha',
    'YuzuhaTanukiInBroadDaylight',
    'Zhao',
    'ZhuYuan',
]

__all__ = ['CHARACTERS']